CREATE TABLE IF NOT EXISTS ROOMTYPE (
ROOMID          INTEGER         NOT NULL,
ROOMTYPE        VARCHAR(15)     NOT NULL,
MAXOCCUPANCY    INTEGER         NOT NULL,
ISSMOKING       SMALLINT(1)     NOT NULL,
PRIMARY KEY (ROOMID));