CREATE TABLE IF NOT EXISTS RESERVATION (
RESERVATIONID          INTEGER       NOT NULL,
CARDNUM                VARCHAR(16)   NOT NULL,
ROOMID                 INTEGER       NOT NULL,
PRICE                  FLOAT,
STARTDATE              DATE          NOT NULL,
ENDDATE                DATE          NOT NULL,
FOREIGN KEY (CARDNUM) REFERENCES CREDIT_CARD (CARDNUM),
FOREIGN KEY (ROOMID) REFERENCES ROOMTYPE (ROOMID),
PRIMARY KEY (RESERVATIONID));